set(CMAKE_LINKER_TYPE lld)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_USING_LINKER_lld -fuse-ld=lld)
set(CMAKE_CXX_USING_LINKER_lld -fuse-ld=lld)
# set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
# set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lc++ -lc++abi")
